spring:
  application:
    name: movies-ms
  datasource:
    url: jdbc:mysql://localhost:3306/dssdb?useSSL=false
    username: matlab
    password: matlab
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
server:
  port: 8083